"""workspace

Creates the `workspaces` table — WP12a, the primary tenancy boundary
(D01, APPROVED — CLOSED) that every Gate C entity's `workspace_id`
references.

Hand-written rather than autogenerated: `alembic revision --autogenerate`
requires a live database connection, which was not available in the
environment this was authored in. The DDL below was verified against
`Base.metadata` by `alembic upgrade head --sql` (offline mode) and by
`backend/tests/test_workspace_model.py`, which asserts the emitted schema
matches the ORM model field-for-field.

Note on `owner_id`: it is indexed but carries **no FOREIGN KEY
constraint**. This is deliberate, not an oversight — the `users` table
does not exist until WP16 (Minimal Identity and Authentication), so there
is nothing to reference yet. WP16's own migration adds the constraint.
Creating a FK here would fail against a clean database.

Revision ID: b1c4f7a2e9d3
Revises: e0aa881262f5
Create Date: 2026-08-02

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1c4f7a2e9d3"
down_revision: str | Sequence[str] | None = "e0aa881262f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "workspaces",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_index(
        op.f("ix_workspaces_owner_id"),
        "workspaces",
        ["owner_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_workspaces_owner_id"), table_name="workspaces")
    op.drop_table("workspaces")
