"""enterprise_object

Creates the `enterprise_objects` table — WP13, as amended by A-01
(`MVP_WORK_PACKAGE_PLAN.md` § Gate C — Amendments): the acceptance
criteria's `status` field is `phase`, governed by ADR-0009.

Hand-written rather than autogenerated: `alembic revision --autogenerate`
needs a live database connection, which the authoring environment did not
have. The DDL was verified against `Base.metadata` by
`alembic upgrade --sql head` (offline mode) and by
`backend/tests/test_enterprise_object_model.py`, which asserts the emitted
schema matches the ORM model field-for-field.

Three deliberate choices, recorded here so they read as decisions rather
than omissions:

- **`workspace_id` has a real FOREIGN KEY**, unlike `Workspace.owner_id`.
  The `workspaces` table exists as of WP12a (revision b1c4f7a2e9d3, this
  migration's direct parent), so there is a table to point at. ADR-0004
  requires the scoping; D01 makes Workspace the isolation boundary.

- **`owner_id` has no FOREIGN KEY.** Same reason as WP12a: the `users`
  table does not exist until WP16 (Minimal Identity and Authentication).
  Creating the constraint now would fail against a clean database. WP16's
  own migration adds it.

- **`phase` is a CHECK-constrained VARCHAR, not a Postgres ENUM.** Per
  ADR-0009 §6: the value set is newly derived from D10 §6, and a CHECK is
  alterable in one migration where an ENUM makes value removal effectively
  irreversible. `type` carries no CHECK at all — no approved source
  enumerates Enterprise Object's specializations, and inventing that set
  here would introduce domain concepts inside a frozen domain model.

Revision ID: c3e8b5d1f704
Revises: b1c4f7a2e9d3
Create Date: 2026-08-02

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3e8b5d1f704"
down_revision: str | Sequence[str] | None = "b1c4f7a2e9d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "enterprise_objects",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column(
            "phase",
            sa.String(length=32),
            server_default="active",
            nullable=False,
        ),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "phase IN ('active', 'archived', 'superseded')",
            name=op.f("ck_enterprise_objects_phase_is_known"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_enterprise_objects_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enterprise_objects")),
    )
    op.create_index(
        op.f("ix_enterprise_objects_workspace_id"),
        "enterprise_objects",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enterprise_objects_owner_id"),
        "enterprise_objects",
        ["owner_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_enterprise_objects_owner_id"), table_name="enterprise_objects"
    )
    op.drop_index(
        op.f("ix_enterprise_objects_workspace_id"), table_name="enterprise_objects"
    )
    op.drop_table("enterprise_objects")
