"""identity_and_membership

Creates the `users` and `workspace_memberships` tables, and backfills the
`owner_id` foreign key on `workspaces` and `enterprise_objects` that both
prior migrations explicitly deferred to this one -- WP16, as amended by
A-03 (`MVP_WORK_PACKAGE_PLAN.md` Section Gate C -- Amendments): the
schema-foundation half of WP16 only. Login, auth middleware, and
`ActorContext` resolution are not part of this migration.

Hand-written rather than autogenerated, same reason as WP13's migration:
no live database connection in the authoring environment. Verified
against `Base.metadata` via `alembic upgrade --sql head` (offline mode)
and by `backend/tests/test_user_model.py` /
`test_workspace_membership_model.py`, which assert the emitted schema
matches the ORM models field-for-field.

Deliberate choices, recorded here so they read as decisions rather than
omissions:

- **`users` carries only `id`, `created_at`, `updated_at`.** ADW-02
  (Identity and Workspace Boundary), the domain workshop that owns
  identity/credential mechanics, is unwritten. No approved source
  specifies any other field. See `app/models/user.py`.

- **`workspace_memberships.role` is a CHECK-constrained VARCHAR
  permitting exactly one value, `owner`.** ADR-0010 ships the column but
  does not approve GC-004 (single scalar `role` vs. a role-assignment
  join table) -- that stays open until a second role exists. A CHECK,
  not an ENUM, per the same reversibility reasoning as
  `enterprise_objects.phase` (ADR-0009 Section 6).

- **`workspace_memberships` carries no `updated_at`.** Matches
  `docs/c4/C3_COMPONENT.md`'s already-resolved shape exactly (five
  columns, no more) -- not an inconsistency with `workspaces` /
  `enterprise_objects` carrying one, a deliberate fidelity choice. See
  `app/models/workspace_membership.py`.

- **`workspaces.owner_id` and `enterprise_objects.owner_id` gain a real
  FOREIGN KEY to `users.id` here, added via ALTER rather than declared at
  table-creation time** -- those tables were created before `users`
  existed, exactly as their own migrations' comments said would happen.

Revision ID: d21a6f4c9e8b
Revises: c3e8b5d1f704
Create Date: 2026-08-03

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d21a6f4c9e8b"
down_revision: str | Sequence[str] | None = "c3e8b5d1f704"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )

    op.create_table(
        "workspace_memberships",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner')",
            name=op.f("ck_workspace_memberships_role_is_known"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_memberships_workspace_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workspace_memberships_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_memberships")),
        sa.UniqueConstraint(
            "workspace_id",
            "user_id",
            name=op.f("uq_workspace_memberships_workspace_id"),
        ),
    )
    op.create_index(
        op.f("ix_workspace_memberships_workspace_id"),
        "workspace_memberships",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_memberships_user_id"),
        "workspace_memberships",
        ["user_id"],
        unique=False,
    )

    op.create_foreign_key(
        op.f("fk_workspaces_owner_id_users"),
        "workspaces",
        "users",
        ["owner_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_enterprise_objects_owner_id_users"),
        "enterprise_objects",
        "users",
        ["owner_id"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        op.f("fk_enterprise_objects_owner_id_users"),
        "enterprise_objects",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_workspaces_owner_id_users"), "workspaces", type_="foreignkey"
    )

    op.drop_index(
        op.f("ix_workspace_memberships_user_id"),
        table_name="workspace_memberships",
    )
    op.drop_index(
        op.f("ix_workspace_memberships_workspace_id"),
        table_name="workspace_memberships",
    )
    op.drop_table("workspace_memberships")

    op.drop_table("users")
